definitions:
  faq:
    type: object
    title: faq
    required:
      - question
      - answer
    properties:
      question:
        type: string
      answer:
        type: string
  skill:
    type: object
    name: skill
    required:
      - level
      - name
    properties:
      skill:
        type: string
      level:
        type: string
